version: "3.7"
services:
  auth-service:
    build:
      context: $PROJECT_ROOT
      dockerfile: scripts/docker/auth-service.dockerfile
    image: $DOCKER_REGISTRY/auth-service
    env_file:
      - .env

  chat-service:
    build:
      context: $PROJECT_ROOT
      dockerfile: scripts/docker/chat-service.dockerfile
    image: $DOCKER_REGISTRY/chat-service
    env_file:
      - .env
    entrypoint: /chat-service --chat-service-port $chat_service_port --redis-port 6379
    depends_on:
      - redis
    ports:
      - "$chat_service_port:$chat_service_port"

  redis:
    image: redis:alpine
