version: "3.7"
services:
  auth:
    build:
      context: $PROJECT_ROOT
      dockerfile: scripts/docker/auth.dockerfile
    image: serika-registry:443/auth
    env_file:
      - .env

  chat-service:
    build:
      context: $PROJECT_ROOT
      dockerfile: scripts/docker/chat.dockerfile
    image: serika-registry:443/chat
    env_file:
      - .env
#    entrypoint: /chat-service --chat-service-port $chat_service_port --redis-port 6379
    depends_on:
      - redis

  redis:
    image: redis:alpine
