version: "3.7"
services:
  auth-service:
    build:
      context: $PROJECT_ROOT
      dockerfile: scripts/docker/auth-service.dockerfile
    image: serikaron/auth-service
    env_file:
      - .env

  chat-service:
    build:
      context: $PROJECT_ROOT
      dockerfile: scripts/docker/chat-service.dockerfile
    image: serikaron/chat-service
    env_file:
      - .env
