version: "3.7"
services:
  auth:
    build:
      context: $PROJECT_ROOT
      dockerfile: scripts/docker/auth.dockerfile
    image: serika-registry:443/auth
    env_file:
      - .env

  auth-test:
    build:
      context: $PROJECT_ROOT
      dockerfile: scripts/docker/auth.test.dockerfile
    image: serika-registry:443/auth-test
    env_file:
      - .env
    depends_on:
      - auth

