version: "3.7"
services:
  auth:
    build:
      context: $PROJECT_ROOT
      dockerfile: scripts/docker/auth.dockerfile
    image: $DOCKER_REGISTRY/auth
    env_file:
      - .env
    networks:
      - end-to-end-test

  chat:
    build:
      context: $PROJECT_ROOT
      dockerfile: scripts/docker/chat.dockerfile
    image: $DOCKER_REGISTRY/chat
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - end-to-end-test

  redis:
    image: redis:alpine
    networks:
      - end-to-end-test

  end-to-end:
    build:
      context: $PROJECT_ROOT
      dockerfile: scripts/docker/end.to.end.test.dockerfile
    image: $DOCKER_REGISTRY/end-to-end
    env_file:
      - .env
    networks:
      - end-to-end-test

networks:
  end-to-end-test: