version: "3.7"
services:
  redis-test:
    build:
      context: .
      dockerfile: redis-test/Dockerfile
    image: redis-test
    environment:
      - redis_port=6379
    depends_on:
      - redis

  redis:
    image: redis:alpine

